---
- name: Configure PXEboot box
  hosts: all
  become: yes
  roles:
    - { role: yum_packages, tags: ['yum'] }
    - { role: pxe_configure, tags: ['pxe'], ubuntu_artful_image: true, gentoo_image: false, ubuntu_xenial_image: true }
